# Step 1: Build Vite app
FROM node:22-alpine AS build

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build




FROM node:18-alpine AS production
WORKDIR /app

# Install only the server dependency
RUN npm install -g serve

# Copy the build output from the previous stage
COPY --from=build /app/dist ./dist

# Expose the port Cloud Run or Docker will use
EXPOSE 3000

# Start the app
CMD ["serve", "-s", "dist", "-l", "3000"]

# Remove dev dependencies and install only production dependencies
# RUN npm ci --only=production
# RUN npm install -g serve
# # Expose port (Cloud Run will set PORT env variable)
# EXPOSE 3000
# CMD ["npm", "start"]
# 